FROM debian:bullseye
ARG QDK_VERSION="2.4.0"

RUN apt-get update
RUN apt-get install -y wget rsync unzip python2 xz-utils tar
RUN wget -O /tmp/qdk.zip https://github.com/qnap-dev/QDK/archive/refs/tags/v${QDK_VERSION}.zip
RUN unzip -d /tmp /tmp/qdk.zip
RUN rm -rf /tmp/qdk.zip

RUN chmod 755 /tmp/QDK-${QDK_VERSION}/InstallToUbuntu.sh
RUN cd /tmp/QDK-${QDK_VERSION} && ./InstallToUbuntu.sh install;
RUN rm -rf /tmp/QDK-${QDK_VERSION}

ENTRYPOINT [""]
