
FROM debian:bookworm-20250929
COPY ./copy.sh /copy.sh
COPY ./jellyfin-server-steps.sh /jellyfin-server-steps.sh
COPY ./jellyfin-ffmpeg-steps.sh /jellyfin-ffmpeg-steps.sh
COPY ./packaging /packaging

ENTRYPOINT [""]
